# Generated by Django 6.1.1 on 2026-09-20 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='otp',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='OTP must be exactly 6 digits.', regex='^\\d{6}$')]),
        ),
    ]
