# Generated by Django 6.1.1 on 2026-09-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_emailotp_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
