# Generated by Django 6.1.1 on 2026-09-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='last_modified',
            new_name='updated_at',
        ),
    ]
